FROM alpine:latest
ENV APP_HOME /app

RUN apk update \
    && apk add ruby-full ruby-dev alpine-sdk ruby-bundler \
    && gem install bundler --no-ri --no-rdoc \
    && mkdir $APP_HOME && cd $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
