kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: +IcOUDNn0rFpTcR/3Mo62p1qB1jRyE7ieDyxZNyFstA=
      - identity: {}
